# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161121_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(default='Dr.Pavagada Prakash Rao', max_length=30)),
                ('price', models.CharField(max_length=6)),
                ('book_id', models.CharField(max_length=20)),
                ('publications', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
