# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='published_date',
            field=models.DateField(),
        ),
    ]
