# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161122_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img_id',
            field=models.CharField(default="{% static 'css/slider1.jpg' %}", max_length=1000),
        ),
    ]
