# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_shop_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
