# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161122_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=100)),
                ('timing', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=400)),
            ],
        ),
    ]
